version: "3"

services:
  gitea:
    image: gitea/gitea:1.15.10-rootless
    restart: always
    volumes:
      - ./data:/var/lib/gitea
      - ./config:/etc/gitea
      - ./custom:/var/lib/gitea/custom 
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3000:3000
      - 2222:2222
    env_file:
      - gitea.env
    networks:
      - proxy-tier
      - maria

networks:
  proxy-tier:
    external:
      name: proxy-tier
  maria:
    external:
      name: maria
