version: "3"

services:
  gitea:
    image: gitea/gitea:1.18.0-rootless
    restart: always
    volumes:
      - gitea-data:/var/lib/gitea
      - gitea-config:/etc/gitea
        #- ./custom:/var/lib/gitea/custom 
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3000:3000
      - 2222:2222
    env_file:
      - gitea.env
    networks:
      - proxy-tier
      - maria

volumes:
  gitea-data:
    driver: local
  gitea-config:
    driver: local

networks:
  proxy-tier:
    external:
      name: proxy-tier
  maria:
    external:
      name: maria
